# Generated by Django 5.1.5 on 2025-01-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpmain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpuser",
            name="atcoder_handle",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
