# Generated by Django 5.1.5 on 2025-03-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmain', '0002_cpuser_atcoder_handle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='cpuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='cpuser',
            name='atcoder_handle',
        ),
        migrations.RemoveField(
            model_name='cpuser',
            name='codechef_handle',
        ),
        migrations.RemoveField(
            model_name='cpuser',
            name='codeforces_handle',
        ),
        migrations.RemoveField(
            model_name='cpuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='cpuser',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='cpuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='cpuser',
            name='leetcode_handle',
        ),
        migrations.RemoveField(
            model_name='cpuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='cpuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='cpuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cpuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cpuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cpuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cpuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cpuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
